version: "3"

# DEV

services:

  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - ~/data/dev/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always

  sonarqube:
    image: sonarqube:6.7.5-alpine
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    volumes:
      - ~/data/dev/sonarqube.tmp:/tmp
      - ~/data/dev/sonarqube.plugins:/opt/sonarqube/extensions/plugins
      - ~/data/dev/sonarqube.logs:/opt/sonarqube/logs
      - ~/data/dev/sonarqube.temp:/opt/sonarqube/temp
    restart: always

  jenkins:
    image: jenkins-maven:2.141-alpine-3.5.4
    build: ./jenkins
    ports:
      - "8080:8080"
    depends_on:
      - sonarqube
    volumes:
      - ~/data/dev/jenkins:/var/jenkins_home
      - ~/data/dev/jenkins.root:/root
      - ~/data/dev/maven_repo:/root/.m2
      - ~/data/dev/git_repo:/var/git_repo
    restart: always
